# 游戏服务配置文件

# 应用基础配置
app:
  name: "GreatestWorks MMO Server"
  version: "1.0.0"
  environment: "development"
  debug: true

# 服务器配置
server:
  # HTTP 服务器
  http:
    host: "0.0.0.0"
    port: 8080
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "60s"
  
  # RPC 服务器
  rpc:
    host: "0.0.0.0"
    port: 8081
    max_connections: 1000
    timeout: "30s"
    keep_alive: true
    keep_alive_period: "30s"
    read_timeout: "30s"
    write_timeout: "30s"

# 数据库配置
database:
  # MongoDB 主数据库
  mongodb:
    uri: "mongodb://admin:admin123@mongodb:27017"
    database: "mmo_game"
    username: "admin"
    password: "admin123"
    auth_source: "admin"
    max_pool_size: 100
    min_pool_size: 10
    max_idle_time: "10m"
    connect_timeout: "10s"
    socket_timeout: "30s"
    
  # Redis 缓存
  redis:
    addr: "redis:6379"
    password: "redis123"
    db: 0
    pool_size: 100
    min_idle_conns: 10
    max_retries: 3
    dial_timeout: "5s"
    read_timeout: "3s"
    write_timeout: "3s"
    pool_timeout: "4s"
    idle_timeout: "5m"

# 消息队列配置
messaging:
  # NATS 配置
  nats:
    url: "nats://nats:4222"
    cluster_id: "mmo-cluster"
    client_id: "mmo-server-1"
    max_reconnect: 10
    reconnect_wait: "2s"
    timeout: "5s"
    
    # JetStream 配置
    jetstream:
      enabled: true
      domain: "mmo"
      
    # 主题配置
    subjects:
      player_events: "player.events.>"
      game_events: "game.events.>"
      system_events: "system.events.>"

# 日志配置
logging:
  level: "info"
  format: "json"
  output: "stdout"
  
  fields:
    service: "mmo-server"
    version: "1.0.0"

security:
  jwt:
    secret: "dev-secret-change-me"
    issuer: "greatestworks"
    audience: "players"
    access_token_ttl: "15m"
    refresh_token_ttl: "168h"
  rate_limit:
    enabled: true
    requests_per_minute: 1000
    burst: 100

# 游戏配置
game:
  # 玩家配置
  player:
    max_level: 100
    initial_gold: 1000
    initial_experience: 0
    max_inventory_slots: 100
    
  # 战斗配置
  battle:
    max_battle_time: "10m"
    damage_variance: 0.1
    critical_rate_base: 0.05
    critical_damage_base: 1.5
    
  # 经验配置
  experience:
    base_exp_per_level: 100
    exp_multiplier: 1.2
    max_exp_bonus: 2.0
    
  # 聊天配置
  chat:
    max_message_length: 500
    rate_limit: 10
    banned_words:
      - "spam"
      - "cheat"

# 性能配置
performance:
  # 工作池配置
  worker_pool:
    size: 100
    queue_size: 1000
    
  # 缓存配置
  cache:
    default_ttl: "1h"
    max_entries: 10000
    cleanup_interval: "10m"
    
  # 限流配置
  rate_limit:
    enabled: true
    requests_per_minute: 1000
    burst: 100

# 监控配置
monitoring:
  health:
    enabled: true
    path: "/health"
  metrics: # deprecated legacy settings
    enabled: false
    namespace: "game_service"
  profiling:
    enabled: true
    host: "0.0.0.0"
    port: 6060 # 访问 http://<host>:6060/debug/pprof/{profile,heap,goroutine,block,trace,...}